spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vendor_info_service?useSSL=false
    username: root
    password: password

logging:
  level:
    com:
      example.springdemo.controller: DEBUG

#mvc:
  #pathmatch:
   # matching-strategy: ANT_PATH_MATCHER
  #static-path-patter: /swagger*

  #JPA Settings
  jpa.hibernate.ddl_auto: update

  #MongoDB
  data:
      mongodb:
        host: localhost
        port: 55000
        database: UserDetails
  #data.mongodb.username=username_value  (optional)
  #spring.data.mongodb.password=password_value (optional)

management:
  endpoints:
    web:
      exposure:
        include: "*"